---
- name: "[ {{ sgs.name }} ] Destroying Security Group"
  ali_security_group:
    alicloud_access_key: '{{ access_key }}'
    alicloud_secret_key: '{{ secret_key }}'
    alicloud_region: '{{ region }}'
    group_id: '{{ isgs.groups.0.id }}'
    group_name: '{{ sgs.name }}'
    state: absent
  when:
    - isgs.groups.0.id is defined
