---
- name: "[ {{ islb.load_balancers.0.id }} - {{ vsg.name }} ] Destroying VSG - Configuring Listener"
  include_role:
    name: slb_vsg_listener
  when:
    - vsg.listener is defined

- name: "[ {{ islb.load_balancers.0.id }} - {{ vsg.name }} ] Destroying VSG"
  ali_slb_vsg:
    alicloud_access_key: '{{ access_key }}'
    alicloud_secret_key: '{{ secret_key }}'
    alicloud_region: '{{ region }}'
    load_balancer_id: '{{ islb.load_balancers.0.id }}'
    vserver_group_name: '{{ vsg.name }}'
    backend_servers: '{{ vsg.backend }}'
    state: absent
  when:
    - ivsg.vserver_groups.0.id is defined
