---
- name: "[ {{ attach.id }} - {{ eip.name }} ] Destroying EIP"
  ali_eip:
    alicloud_access_key: '{{ access_key }}'
    alicloud_secret_key: '{{ secret_key }}'
    alicloud_region: '{{ region }}'
    instance_id: '{{ attach.id }}'
    allocation_id: '{{ ieip.eips.0.id }}'
    name: '{{ eip.name }}'
    state: absent
  when:
    - ieip.eips.0.id is defined
