---
- name: VSwitch
  hosts: localhost

  vars_files:
    - vars/01-vpc.yml
    - vars/02-vswitch.yml

  tasks:
    - name: Configuring VSwitch Resource
      include_role:
        name: vswitch
      loop: '{{ zones | flatten(levels=1) }}'
      loop_control:
        loop_var: vsw
