---
- name: ECS
  hosts: localhost

  vars_files:
    - vars/01-vpc.yml
    - vars/05-ecs_public.yml

  tasks:
    - name: Configuring ECS Resource
      include_role:
        name: ecs
      loop: '{{ instance | flatten(levels=1) }}'
      loop_control:
        loop_var: ecs
