---
- name: SLB
  hosts: localhost

  vars_files:
    - vars/01-vpc.yml
    - vars/07-slb_public.yml

  tasks:
    - name: Configuring SLB Resource
      include_role:
        name: slb
      loop: '{{ loadbalancer | flatten(levels=1) }}'
      loop_control:
        loop_var: slb
