---
- name: OSS
  hosts: localhost

  vars_files:
    - vars/01-vpc.yml
    - vars/07-slb_public.yml

  tasks:
    - name: Configuring OSS Bucket Resource
      include_role:
        name: oss_bucket
      loop: '{{ object_storage | flatten(levels=1) }}'
      loop_control:
        loop_var: bucket
