---
slb:
  - name: 'SLB-AP-SEA-5-1-Private'
    type: 'slb.s1.small'
    zone:
      zone_1: 'ap-southeast-5a'   # Master Zone
      zone_2: 'ap-southeast-5b'   # Secondary Zone
    internet:
      enabled: false
    vsg:
      - name: 'VSG-SLB-AP-SEA-5-1-Private-1'
        backend:
          - type: 'ecs'                 # Valid Value can be ecs or eni
            server_id: 'i-xxxxxxxxxxx'  # Valid Value must be valid id of ecs oe eni
            port: 8080
            weight: 100
          - type: 'ecs'                 # Valid Value can be ecs or eni
            server_id: 'i-xxxxxxxxxxx'  # Valid Value must be valid id of ecs oe eni
            port: 8080
            weight: 100
        listener:
          port: 80
          # Valid Value:
          # Should have the same value where the backend server port is listening
          backend_port: 8080
          # Valid Value:
          # tcp       : for TCP based connection
          # udp       : for UDP based connection
          # http      : for HTTP based application
          # https     : fot HTTPS based application
          protocol: 'tcp'
          # Valid Value:
          # wrr       : for Weighted Round-Robin algortihm
          # wlc       : for Weighted Least Connection algorithm
          algorithm: 'wrr'
