---
loadbalancer:
  - name: 'SLB-AP-SEA-5-1'
    type: 'slb.s1.small'
    zone:
      zone_1: 'ap-southeast-5a'   # Master Zone
      zone_2: 'ap-southeast-5b'   # Secondary Zone
    vswitch:
      name: 'VSW-AP-SEA-5A'
    vsg:
      - name: 'SLB-AP-SEA-5-1-VSG-1'
        backend:
          - name: 'ECS-AP-SEA-5-1'
            port: 8080
            weight: 100
    listener:
      - vsg: "SLB-AP-SEA-5-1-VSG-1"
        port: 80
        # Valid Value:
        # Should have the same value where the backend server port is listening
        backend_port: 8080
        # Valid Value:
        # tcp       : for TCP based connection
        # udp       : for UDP based connection
        # http      : for HTTP based application
        # https     : fot HTTPS based application
        protocol: 'tcp'
        # Valid Value:
        # wrr       : for Weighted Round-Robin algortihm
        # wlc       : for Weighted Least Connection algorithm
        algorithm: 'wrr'
        health_check:
          status: on
          type: tcp
          http_code: 'http_2xx'   # Valid Value can be http_2xx or multiple value seperated by coma (,) eg. http_2xx,http_3xx
          port: 80                # If not declared listener backend port will be used
